www/purple_admin/urls.py
from django.urls import path

from purple_admin import views

urlpatterns = [
    path('', views.cabinet, name='admin_panel_cabinet'),
    # Адмника Наименований маршрутов
    path('route_list', views.cabinet_list, {'type': 'route'}, name='admin_panel_route_list'),
    path('route_add', views.cabinet_add, {'type': 'route'}, name='admin_panel_route_add'),
    path('route_edit/<int:pk>/', views.cabinet_edit, {'type': 'route'}, name='admin_panel_route_edit'),
    path('route_delete/<int:pk>/', views.cabinet_delete, {'type': 'route'}, name='admin_panel_route_delete'),
    # Адмника наименований остановок
    path('route_platform_list', views.cabinet_list, {'type': 'route_platform'}, name='admin_panel_route_platform_list'),
    path('route_platform_add', views.cabinet_add, {'type': 'route_platform'}, name='admin_panel_route_platform_add'),
    path('route_platform_edit/<int:pk>/', views.cabinet_edit, {'type': 'route_platform'},
         name='admin_panel_route_platform_edit'),
    path('route_platform_delete/<int:pk>/', views.cabinet_delete, {'type': 'route_platform'},
         name='admin_panel_route_platform_delete'),
    path('route_relation_add_ajax', views.cabinet_add, {'type': 'route_platform_type'},
         name='admin_panel_route_platform_type_relation_ajax_add'),
    # Админка ТС
    path('ts_list', views.cabinet_list, {'type': 'ts'}, name='admin_panel_ts_list'),
    path('ts_add', views.cabinet_add, {'type': 'ts'}, name='admin_panel_ts_add'),
    path('ts_edit/<int:pk>/', views.cabinet_edit, {'type': 'ts'}, name='admin_panel_ts_edit'),
    path('ts_delete/<int:pk>/', views.cabinet_delete, {'type': 'ts'}, name='admin_panel_ts_delete'),
    # Адмника Создания маршрута на карте
    path('map_route_editor_add', views.mapped_route_add, name='admin_panel_mapped_route_add'),
    path('map_route_path_save', views.mapped_route_path_save, name='admin_panel_mapped_path_save'),
]

www/www/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('red/', include('editor.urls')),
    path('api/', include('editor.urls')),
    path('auth/', include('auth_user.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('cabinet/', include('purple_admin.urls')),
    path('index/', RedirectView.as_view(url='frontoffice:index', permanent=True), name='index'),
    path('', include('frontoffice.urls', namespace='frontoffice')),
]

www/route/models.py
from django.db import models


class Route(models.Model):
    """Описывает маршрут как последовательность lonlat точек"""
    name = models.CharField(max_length=100, unique=True, verbose_name='Краткое название маршрута',
                            help_text="Наименование маршрута: 10/2, 9а, 15 и т.д ")
    description = models.TextField(max_length=500, verbose_name='Полное название маршрута',
                                   help_text="Краткое описание маршрута", blank=True)
    STATE_CHOICES = (
        (1, 'Создан, не настроен'),
        (2, 'Задана последовательность остановок'),
        (3, 'Заданы точки на карте'),
    )
    state = models.IntegerField(choices=STATE_CHOICES, default=1, verbose_name='Статус маршрута')

    model_type = 'route'
    model_description = 'Внесение маршрутов в систему'

    class Meta:
        db_table = "route"
        indexes = [models.Index(fields=["name"])]

    @property
    def platforms(self):
        return self.platforms.count()

    def __str__(self):
        return "%s" % self.name


class RoutePlatform(models.Model):
    """Описывает остановки, как lonlat точку
        Используется для связи с точками"""
    name = models.CharField(max_length=100, unique=True, verbose_name="Краткое название остановки",
                            help_text="Название остановки")
    longitude = models.FloatField(help_text="долгота")
    latitude = models.FloatField(help_text="широта")
    description = models.TextField(max_length=500, verbose_name="Развернутое название остановки",
                                   help_text="Краткон описание остановки", blank=True)

    order_number = models.IntegerField(default=1, verbose_name='Порядковый номер остановки  маршрута')

    model_type = 'route_platform'
    model_description = 'Внесение остановок в систему'

    class Meta:
        db_table = "route_platform"
        indexes = [
            models.Index(fields=["name"])
        ]

    def __str__(self):
        return "%s" % self.name


class PlatformType(models.Model):
    """Описывает типы остановок"""
    name = models.CharField(max_length=100, unique=False, verbose_name="Тип остановки",
                            help_text="Название типа остановки")
    description = models.TextField(max_length=500, verbose_name="Описание", help_text="Краткое описани типа остановки",
                                   blank=True)

    model_type = 'route_platform_type'
    model_description = 'Внесение типа остановки'

    class Meta:
        db_table = "platform_type"
        indexes = [models.Index(fields=["name"])]

    def __str__(self):
        return "%s" % self.name


class RoutePoint(models.Model):
    """Описывает маршрут как последовательность lonlat точек"""
    prev = models.ForeignKey("self", on_delete=models.CASCADE, related_name="prev_point",
                             null=True, help_text="предыдущая точка маршрута")
    next = models.ForeignKey("self", on_delete=models.CASCADE, related_name="next_point",
                             null=True, help_text="следующая точка маршрута")
    route = models.ForeignKey(Route, on_delete=models.CASCADE, related_name='points', help_text="ID маршрута")
    route_platform = models.ForeignKey(RoutePlatform, on_delete=models.SET_NULL, null=True, default=None)
    route_platform_type = models.ForeignKey(PlatformType, on_delete=models.SET_NULL, null=True, default=None,
                                            verbose_name="Тип остановки", help_text="ID типа остановки")

    order_number = models.IntegerField(default=1, verbose_name='Порядковый номер точки маршрута')

    longitude = models.FloatField(null=True, verbose_name="Долгота", help_text="долгота")
    latitude = models.FloatField(null=True, help_text="широта")
    description = models.TextField(max_length=500, help_text="Краткое описание точки маршрута", blank=True)

    @property
    def is_platform(self):
        if self.route_platform:
            return True
        else:
            return False

    class Meta:
        db_table = "route_point"
        indexes = [models.Index(fields=["prev", "next", "route"])]

    def __str__(self):
        return "%d %s" % (self.id, self.route.name)


class BusModel(models.Model):
    """Информация о транспортном средстве: UUID, Гос номер, Модель"""
    uuid = models.CharField(max_length=255, verbose_name='ID GPS/GLONASS', help_text='Номер датчика системы слежения',
                            unique=True)
    name = models.CharField(max_length=255, verbose_name='Название ТС',
                            help_text='Сокращенное название для внутренних целей и удобства')
    licenseplate = models.CharField(max_length=55, verbose_name='ГОС номер ТС')
    BUS_TYPE = (
        ("bus", "автобус"),
        ("minibus", "маршрутное такси"),
        ("trolleybus", "троллейбус"),
        ("tramway", "трамвай")
    )
    type = models.CharField(max_length=15, verbose_name='Тип',
                            help_text='Тип транспортного средства (Автобус, Троллейбус)', choices=BUS_TYPE, default=0)
    model = models.CharField(max_length=255, verbose_name='Модель ТС',
                             help_text='Наименование модели ТС (ПАЗ, ЛИАЗ и тд.', blank=True)
    techquality = models.IntegerField(verbose_name='Техническое состояние', choices=(
        (1, "не находу"), (2, "плохое"), (3, "удовлетворительное"), (4, "хорошее"), (5, "отличное")), default=4)

    model_type = 'ts'
    model_description = 'Внесение транспортных средств в систему'

    class Meta:
        db_table = "vehicles"
        indexes = [
            models.Index(fields=["uuid", "name"])
        ]

    def __str__(self):
        return "%s - %s" % (self.uuid, self.name)

www/purple_admin/views.py
import json

from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.forms.models import model_to_dict
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404, Http404

from purple_admin.forms import RouteForm, RoutePlatformForm, PlatformTypeForm, BusModelForm, RoutePlatformFormset
from route.models import PlatformType, Route, RoutePlatform, BusModel, RoutePoint


@login_required
def cabinet(request):
    return render(request, 'admin_panel/cabinet.html')


@login_required
def cabinet_delete(request, pk, type):
    models_by_type = {
        'route': Route,
        'route_platform': RoutePlatform,
        'ts': BusModel
        # 'flat_type': RealEstateFlatTypeModel,
    }
    Model = models_by_type[type]
    objects = get_object_or_404(Model, pk=pk)
    objects.delete()
    if request.is_ajax():
        return JsonResponse({})
    return redirect('admin_panel_' + Model.model_type + '_list')


@login_required
def cabinet_add(request, type):
    models_by_type = {
        'route': Route,
        'route_platform': RoutePlatform,
        'route_platform_type': PlatformType,
        'ts': BusModel,
    }

    form_by_type = {
        'route': RouteForm,
        'route_platform': RoutePlatformForm,
        'route_platform_type': PlatformTypeForm,
        'ts': BusModelForm,
    }

    template_by_type = {
        'route': 'cabinet_form.html',
        'route_platform': 'cabinet_map_form.html',
        'route_platform_type': '_form.html',
    }

    Model = models_by_type[type]
    Form = form_by_type[type]
    template = template_by_type.get(type, 'cabinet_form.html')

    if request.method == 'POST':
        form = Form(request.POST or None, request.FILES or None)
        if form.is_valid():
            config = form.save()
            if request.is_ajax():
                return JsonResponse({"id": config.id, "name": config.name})
            return redirect('admin_panel_' + Model.model_type + '_list')
    else:
        form = Form()
    context = {
        'form': form,
        'description': Model.model_description,
        'model_type': type,
    }
    return render(request, 'admin_panel/' + template, context=context)


@login_required
def cabinet_list(request, type):
    models_by_type = {
        'route': Route,
        'route_platform': RoutePlatform,
        'ts': BusModel,
        # 'flat_type': RealEstateFlatTypeModel,
    }
    model = models_by_type[type]
    objects = model.objects.all()
    context = {
        'objects': objects,
        'model_type': type,
    }
    return render(request, 'admin_panel/cabinet_list.html', context=context)


@login_required
def cabinet_edit(request, pk, type):
    models_by_type = {
        'route': Route,
        'route_platform': RoutePlatform,
        'route_platform_type': PlatformType,
        'ts': BusModel,
    }

    form_by_type = {
        'route': RouteForm,
        'route_platform': RoutePlatformForm,
        'route_platform_type': PlatformTypeForm,
        'ts': BusModelForm,
    }

    template_by_type = {
        'route': 'cabinet_form.html',
        'route_platform': 'cabinet_map_form.html',
        'route_platform_type': '_form.html',
    }

    Model = models_by_type[type]
    Form = form_by_type[type]
    template = template_by_type.get(type, 'cabinet_form.html')

    objects = get_object_or_404(Model, pk=pk)
    if request.method == 'POST':
        form = Form(request.POST or None, request.FILES or None, instance=objects)
        if form.is_valid():
            config = form.save()
            return redirect('admin_panel_' + Model.model_type + '_list')
    else:
        form = Form(instance=objects)
    context = {
        'form': form,
        'description': Model.model_description,
        'model_type': type,
    }
    return render(request, 'admin_panel/' + template, context=context)


@login_required
def ajax_add(request, type):
    # models_by_type = {
    #     'object': RealEstateObjectModel,
    #     'object_type': RealEstateObjectTypeModel,
    #     'flat_type': RealEstateFlatTypeModel,
    # }

    form_template_type = {
        'route': 'forms/_route_form.html',
        'route_platform': '_map_form.html',
        # 'flat_type': '_flat_form.html',
    }

    form_by_type = {
        'route': RouteForm,
        'route_platform': RoutePlatformForm,
        # 'flat_type': RealEstateFlatTypeForm,
    }

    # Model = models_by_type[type]
    Form = form_by_type[type]
    template = form_template_type[type]

    # type = 'realestate' if type == 'flat_type' else type

    if request.is_ajax():
        if request.method == 'POST':
            form = Form(request.POST, request.FILES)
            if form.is_valid():
                form = form.save()
                return JsonResponse(model_to_dict(form))
            else:
                form = Form()
        else:
            return
    else:
        if request.method == 'POST':
            form = Form(request.POST, request.FILES)
            if form.is_valid():
                form = form.save()
                # form.create_relations_by_string_ids(request.POST.get('flats', None))
                return redirect('admin_panel_' + type + '_list')
        return redirect('admin_panel_cabinet')
    context = {
        'form': form,
        'model_type': Form.Meta.model.model_type,
        'model_description': Form.Meta.model.model_description,
    }
    return render(request, 'admin_panel/' + template, context=context)


def mapped_route_add(request):
    """
    Страница конструктора, которая позволит задавать последовательность остановок,
    Далее, открыть карту и построить промежуточные маршруты,
    Подтвердить и исходранить маршрут в БД.
    :param request:
    :return: Template of constructor
    """

    template_name = 'admin_panel/mapper_route_add.html'
    if request.method == 'GET':
        # route_form = RouteSelectForm(request.GET or None)
        routes = Route.objects.all()
        formset = RoutePlatformFormset(queryset=RoutePoint.objects.none())
    elif request.method == 'POST':
        # route_form = RouteSelectForm(request.POST)
        route_id = request.POST.get('route')
        route = get_object_or_404(Route, pk=route_id)
        formset = RoutePlatformFormset(request.POST)
        platform = PlatformType.objects.get(pk=1)  # default platform name
        platform_endpoint = PlatformType.objects.get(pk=3)  # default platform endpoint name
        last_route_point = None
        if formset.is_valid():
            # route = route_form.save()
            for num, form in enumerate(formset, start=1):
                route_point = form.save(commit=False)
                route_point.latitude = route_point.route_platform.latitude
                route_point.longitude = route_point.route_platform.longitude
                route_point.route = route
                # first iteration
                if num == 1:
                    route_point.route_platform_type = platform_endpoint
                # last iteration
                if num == len(formset):
                    route_point.route_platform_type = platform_endpoint
                route_point.save()
                if last_route_point:
                    last_route_point.next = route_point
                    route_point.prev = last_route_point
                    last_route_point.save()
                    route_point.save()
                last_route_point = route_point
            if request.is_ajax():
                response = serializers.serialize("json", route.points.all())
                return JsonResponse(response, safe=False)
            return redirect('admin_panel_cabinet')
    return render(request, template_name, {
        'routes': routes,
        'formset': formset,
    })


def mapped_route_path_save(request):
    if request.method == 'POST' and request.is_ajax():
        points = json.loads(request.body)
        middle_point_state = False
        current_point = None
        last_point = None
        for p in points:
            if p.get('context') and not middle_point_state:
                middle_point_state = True
                current_point = get_object_or_404(RoutePoint, pk=p['context'].get('id'))
            elif p.get('context'):
                middle_point_state = False
                current_point = get_object_or_404(RoutePoint, pk=p['context'].get('id'))
            elif current_point:
                current_point = RoutePoint(route=current_point.route, latitude=p.get('latitude'), longitude=p.get('longitude'))
                current_point.save()
            if last_point:
                last_point.next = current_point
                current_point.prev = last_point
                last_point.save()
                current_point.save()
            last_point = current_point
        return JsonResponse({'status': 'success'})
    return Http404

www/purple_admin/templates/admin_panel/js/ajax_add.html
<script>
    $(function () {
        $.ajaxSetup({
            headers: {"X-CSRFToken": getCookie("csrftoken")}
        });

        function getCookie(c_name) {
            if (document.cookie.length > 0) {
                c_start = document.cookie.indexOf(c_name + "=");
                if (c_start != -1) {
                    c_start = c_start + c_name.length + 1;
                    c_end = document.cookie.indexOf(";", c_start);
                    if (c_end == -1) c_end = document.cookie.length;
                    return unescape(document.cookie.substring(c_start, c_end));
                }
            }
            return "";
        }

    });
</script>

www/purple_admin/templates/admin_panel/js/ajax_edit.html
<script>
    $(function () {
        $('.ajax_edit').click(function () {
            $('.ajax-body').hide();

            var pk = $(this).attr('pk');

            var lat = 55.747571;
            var lng = 37.628141;

            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(showPosition);
            }

            function showPosition(position) {
                {#TODO: Отключен вывод по геолокации#}
                lat = position.coords.latitude;
                lng = position.coords.longitude;
            }

            $.ajax({
                method: "POST",
                url: "{% url 'admin_panel_realestate_edit'%}" + pk + "/"
            })
                .done(function (msg) {
                        $('.ajax-body').html(msg);

                        var mymap = L.map('mapid').setView([lat, lng], 10);

                        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
                            maxZoom: 18,
                            attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
                                '<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
                                'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
                            id: 'mapbox.streets'
                        }).addTo(mymap);

                        var marker = new L.marker([$("#id_latitude").val(), $("#id_longitude").val()]);
                        marker.addTo(mymap);
                        mymap.on('click', function (ev) {
                            if (marker) { // check
                                mymap.removeLayer(marker); // remove
                            }
                            marker = new L.marker(ev.latlng); // set
                            marker.addTo(mymap);
                            $("#id_latitude").val(ev.latlng.lat);
                            $("#id_longitude").val(ev.latlng.lng);
                        });
                        $('.ajax-body').show(300);
                        setTimeout(function () {
                            mymap.invalidateSize();
                        }, 350);
                        $("html, body").animate({scrollTop: 0}, "slow");
                        {#$('.ajax_overlay').addClass('d-none');#}
                        {#var phoneMask = new IMask(#}
                        {#    document.getElementById('id_phone'), {#}
                        {#        mask: '+{7}(000)000-00-00'#}
                        {#    });#}
                    }
                );
        });

    });
</script>

www/purple_admin/templates/admin_panel/js/ajax_relation.html
<script>
    $(function () {
        $('body').on('submit', 'form#flatform', function (event) {
            {#console.log('click');#}
            {#$(this).parents('form')[0].submit(function (event) {#}
            // Stop form from submitting normally
            event.preventDefault();

            // Get some values from elements on the page:
            var $form = $(this),
                term = $form.serialize(),
                url = $form.attr("action");
            // Send the data using post
            var posting = $.post(url, term);
            // Put the results in a div
            posting.done(function (data) {
                {#var content = $(data).find("#content");#}
                {#$("#result").empty().append(content);#}
                $('#id_type').append(`<option value="${data.id}">${data.name}</option>`);
                {#console.log(relations);#}
                {#relations.val(relations_val);#}
                $('.relation_types').hide(300);
            });
        });
    });
    $('body').on('click', 'div.ajax_relation', function (e) {
        {#$('.ajax_relation').on('click', (function relation() {#}

        $('.relation_types').hide();

        $.ajax({
            method: "POST",
            url: "{% url 'admin_panel_route_platform_type_relation_ajax_add' %}"
        })
            .done(function (msg) {
                    $('.relation_types').html(msg);
                    $('.relation_types').show(300);
                }
            );
    });

    {#$('body').on('click', 'span.ajax_relation_delete', function (e) {#}
    {#    var pk = $(this).attr('pk');#}
    {#    var to_delete = $(this).parents('.delete')[0];#}
    {#    $(to_delete).html('');#}
    {#    $.ajax({#}
    {#        method: "POST",#}
    {#        url: "/cabinet/relation_delete/" + pk + '/'#}
    {#    })#}
    {# });#}


</script>